version: '2'

services:
   liberty-clone1:
      image: liberty
      volumes:
        - /Users/a9886547/Documents/dockerimages/apps:/config/dropins
      ports:
        - 9080:9080
        - 9443:9443

   liberty-clone2:
      image: liberty
      volumes:
        - /Users/a9886547/Documents/dockerimages/apps:/config/dropins
      ports:
        - 9180:9080
        - 9543:9443

   liberty-clone3:
      image: liberty
      volumes:
        - /Users/a9886547/Documents/dockerimages/apps:/config/dropins
      ports:
        - 9280:9080
        - 9643:9443
