version: '2'

services:
   liberty-clone1:
      image: liberty
      ports:
        - 9080:9080
        - 9443:9443

   liberty-clone2:
      image: liberty
      ports:
        - 9180:9080
        - 9543:9443

   libertyLB:
      image: rancher/lb-service-haproxy:v0.7.9
      ports:
        - 80:80

