version: '2'

services:
   liberty-clone1:
      build: .
      ports:
        - 9080:9080
        - 9443:9443

   liberty-clone2:
      build: .
      ports:
        - 9180:9080
        - 9543:9443

   liberty-clone3:
      build: .
      ports:
        - 9280:9080
        - 9643:9443
