version: '3'

services:
   jenkins:
      build: .
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker
        - /usr/local/bin/rancher-compose:/usr/local/bin/rancher-compose
      ports:
        - 8080:8080
      secrets:
      - jenkins-user
      - jenkins-pass
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
