version: '3'

services:
   jenkins:
      build: .
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker
        - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
        - /usr/local/bin/rancher-compose:/usr/local/bin/rancher-compose
      ports:
        - 8070:8080
