version: '3.1'

services:
   jenkins:
      image: jenkins_auto
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/local/bin/docker
        - /usr/local/bin/rancher-compose:/usr/local/bin/rancher-compose
        - /Users/a9886547/apache-maven-3.5.2:/usr/apache-maven
        - /usr/java/jre1.8.0_151:/usr/java/jre
      ports:
        - 8080:8080
      secrets:
      - jenkins-user
      - jenkins-pass
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
